# Problem Statement

The data scientists at BigMart have collected 2013 sales data for 1559 products across 10 stores in different cities. Also, certain attributes of each product and store have been defined. The aim is to build a predictive model and find out the sales of each product at a particular store.

Using this model, BigMart will try to understand the properties of products and stores which play a key role in increasing sales.

 
Please note that the data may have missing values as some stores might not report all the data due to technical glitches. Hence, it will be required to treat them accordingly.

### importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df_train = pd.read_csv('Train.csv')
df_test = pd.read_csv('Test.csv')

In [3]:
df_train.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [4]:
df_test.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3

In [5]:
df_train.shape

(8523, 12)

In [6]:
df_test.shape

(5681, 11)

In [7]:
df_train2 = df_train.drop('Item_Outlet_Sales',axis=1)

In [8]:
combined = df_train2.append(df_test)

In [9]:
combined.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1

In [10]:
combined.tail()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
5676,FDB58,10.5,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.6,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.0,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.3,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.5,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1

In [11]:
combined.reset_index(inplace=True)

In [12]:
combined.drop('index',inplace=True, axis=1)

In [13]:
combined.tail()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
14199,FDB58,10.5,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
14200,FDD47,7.6,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
14201,NCO17,10.0,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1
14202,FDJ26,15.3,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1
14203,FDU37,9.5,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1

In [14]:
combined.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type'],
      dtype='object')

In [15]:
combined['Item_Fat_Content'].value_counts()

Low Fat    8485
Regular    4824
LF          522
reg         195
low fat     178
Name: Item_Fat_Content, dtype: int64

In [16]:
fat_content = {'Low Fat':0, 'LF':0, 'low fat':0, 'Regular':1, 'reg':1}
combined['Item_Fat_Content'] = combined['Item_Fat_Content'].map(fat_content)

In [17]:
combined.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDA15,9.30,0,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,DRC01,5.92,1,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2
2,FDN15,17.50,0,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1
3,FDX07,19.20,1,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store
4,NCD19,8.93,0,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1

In [18]:
combined.isnull().sum()

Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [19]:
combined.tail()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
14199,FDB58,10.5,1,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
14200,FDD47,7.6,1,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
14201,NCO17,10.0,0,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1
14202,FDJ26,15.3,1,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1
14203,FDU37,9.5,1,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1

In [20]:
combined.loc[combined['Item_Identifier'] == 'NCO17']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
182,NCO17,NaN,0,0.128478,Health and Hygiene,117.944,OUT019,1985,Small,Tier 1,Grocery Store
361,NCO17,10.0,0,0.073380,Health and Hygiene,118.244,OUT046,1997,Small,Tier 1,Supermarket Type1
892,NCO17,NaN,0,0.073024,Health and Hygiene,121.844,OUT027,1985,Medium,Tier 3,Supermarket Type3
968,NCO17,10.0,0,0.000000,Health and Hygiene,120.644,OUT035,2004,Small,Tier 2,Supermarket Type1
2076,NCO17,10.0,0,0.073795,Health and Hygiene,121.444,OUT017,2007,NaN,Tier 2,Supermarket Type1
6916,NCO17,10.0,0,0.073494,Health and Hygiene,118.344,OUT049,1999,Medium,Tier 1,Supermarket Type1
7193,NCO17,10.0,0,0.073679,Health and Hygiene,120.944,OUT018,2009,Medium,Tier 3,Supermarket Type2
11573,NCO17,10.0,0,0.000000,Health and Hygiene,118.744,OUT013,1987,High,Tier 3,Supermarket Type1
14201,NCO17,10.0,0,0.073529,Health and Hygiene,118.744,OUT045,2002,NaN,Tier 2,Supermarket Type1

In [21]:
import math
dic = {}

for i in combined['Item_Identifier']:
    a = (combined['Item_Identifier'] == i)
    b = combined[a == True]
    c = b['Item_Weight'].unique()
    for j in c:
        if math.isnan(j):
            continue
        else:
            dic[i] = j


# dic = {}
# for i in alldata['Item_Identifier']:
#     a = (alldata['Item_Identifier']==i)
#     b = alldata[a==True]
#     c = b['Item_Weight'].unique()
#     dic[i] = c

In [22]:
for i in dic:
    combined['Item_Weight'].loc[combined['Item_Identifier'] == i] = dic[i]

/home/suraj333/Documents/dataSci_cource/data/lib/python3.6/site-packages/pandas/core/indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [25]:
combined.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [45]:
pd.crosstab(combined['Outlet_Size'], combined['Outlet_Type'], dropna=False, margins=True)

Outlet_Type,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3,All
Outlet_Size,,,,,
High,0,1553,0,0,1553
Medium,0,1550,1546,1559,4655
Small,1805,3100,0,0,4905
All,1805,9294,1546,1559,14204

In [ ]:
pd.crosstab(combined['Outlet_Size'], combined['Outlet_Type'], dropna=False, margins=True)

In [44]:
combined['Outlet_Size'].isnull().sum()

3091

In [53]:
combined['Outlet_Size'].value_counts()

Small     4905
Medium    4655
High      1553
Name: Outlet_Size, dtype: int64

In [36]:
combined['Outlet_Type'].value_counts()

Supermarket Type1    9294
Grocery Store        1805
Supermarket Type3    1559
Supermarket Type2    1546
Name: Outlet_Type, dtype: int64

In [51]:
combined.groupby('Outlet_Type').Outlet_Size.value_counts()

Outlet_Type        Outlet_Size
Grocery Store      Small          1805
Supermarket Type1  Small          3100
                   High           1553
                   Medium         1550
Supermarket Type2  Medium         1546
Supermarket Type3  Medium         1559
Name: Outlet_Size, dtype: int64

In [52]:
combined.groupby('Outlet_Size').Outlet_Type.value_counts()

Outlet_Size  Outlet_Type
High         Supermarket Type1    1553
Medium       Supermarket Type3    1559
             Supermarket Type1    1550
             Supermarket Type2    1546
Small        Supermarket Type1    3100
             Grocery Store        1805
Name: Outlet_Type, dtype: int64

In [56]:
combined['Outlet_Size'].fillna('Medium', inplace=True)

In [57]:
pd.crosstab(combined['Outlet_Size'], combined['Outlet_Type'], dropna=False, margins=True)

Outlet_Type,Grocery Store,Supermarket Type1,Supermarket Type2,Supermarket Type3,All
Outlet_Size,,,,,
High,0,1553,0,0,1553
Medium,0,4641,1546,1559,7746
Small,1805,3100,0,0,4905
All,1805,9294,1546,1559,14204

In [58]:
pd.crosstab(combined['Outlet_Size'], combined['Outlet_Location_Type'], dropna=False, margins=True)

Outlet_Location_Type  Tier 1  Tier 2  Tier 3    All
Outlet_Size
High                       0       0    1553   1553
Medium                  1550    3091    3105   7746
Small                   2430    1550     925   4905
All                     3980    4641    5583  14204

In [59]:
pd.crosstab(combined['Outlet_Type'], combined['Outlet_Location_Type'], dropna=False, margins=True)

Outlet_Location_Type  Tier 1  Tier 2  Tier 3    All
Outlet_Type
Grocery Store            880       0     925   1805
Supermarket Type1       3100    4641    1553   9294
Supermarket Type2          0       0    1546   1546
Supermarket Type3          0       0    1559   1559
All                     3980    4641    5583  14204

In [60]:
combined.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [61]:
combined.loc[combined['Outlet_Type']=='Grocery Store', 'Outlet_Size'] = 'Small'

In [62]:
combined.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [63]:
combined

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDA15,9.300,0,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,DRC01,5.920,1,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2
2,FDN15,17.500,0,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1
3,FDX07,19.200,1,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Small,Tier 3,Grocery Store
4,NCD19,8.930,0,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1
5,FDP36,10.395,1,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2
6,FDO10,13.650,1,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1
7,FDP10,19.000,0,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3
8,FDH17,16.200,1,0.016687,Frozen Foods,96.9726,OUT045,2002,Medium,Tier 2,Supermarket Type1
9,FDU28,19.200,1,0.094450,Frozen Foods,187.8214,OUT017,2007,Medium,Tier 2,Supermarket Type1
10,FDY07,11.800,0,0.000000,Fruits and Vegetables,45.5402,OUT049,1999,Medium,Tier 1,Supermarket Type1
11,FDA03,18.500,1,0.045464,Dairy,144.1102,OUT046,1997,Small,Tier 1,Supermarket Type1
12,FDX32,15.100,1,0.100014,Fruits and Vegetables,145.4786,OUT049,1999,Medium,Tier 1,Supermarket Type1
13,FDS46,17.600,1,0.047257,Snack Foods,119.6782,OUT046,1997,Small,Tier 1,Supermarket Type1
14,FDF32,16.350,0,0.068024,Fruits and Vegetables,196.4426,OUT013,1987,High,Tier 3,Supermarket Type1
15,FDP49,9.000,1,0.069089,Breakfast,56.3614,OUT046,1997,Small,Tier 1,Supermarket Type1
16,NCB42,11.800,0,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2
17,FDP49,9.000,1,0.069196,Breakfast,54.3614,OUT049,1999,Medium,Tier 1,Supermarket Type1
18,DRI11,8.260,0,0.034238,Hard Drinks,113.2834,OUT027,1985,Medium,Tier 3,Supermarket Type3
19,FDU02,13.350,0,0.102492,Dairy,230.5352,OUT035,2004,Small,Tier 2,Supermarket Type1
20,FDN22,18.850,1,0.138190,Snack Foods,250.8724,OUT013,1987,High,Tier 3,Supermarket Type1
21,FDW12,8.315,1,0.035400,Baking Goods,144.5444,OUT027,1985,Medium,Tier 3,Supermarket Type3
22,NCB30,14.600,0,0.025698,Household,196.5084,OUT035,2004,Small,Tier 2,Supermarket Type1
23,FDC37,15.500,0,0.057557,Baking Goods,107.6938,OUT019,1985,Small,Tier 1,Grocery Store
24,FDR28,13.850,1,0.025896,Frozen Foods,165.0210,OUT046,1997,Small,Tier 1,Supermarket Type1
25,NCD06,13.000,0,0.099887,Household,45.9060,OUT017,2007,Medium,Tier 2,Supermarket Type1
26,FDV10,7.645,1,0.066693,Snack Foods,42.3112,OUT035,2004,Small,Tier 2,Supermarket Type1
27,DRJ59,11.650,0,0.019356,Hard Drinks,39.1164,OUT013,1987,High,Tier 3,Supermarket Type1
28,FDE51,5.925,1,0.161467,Dairy,45.5086,OUT010,1998,Small,Tier 3,Grocery Store
29,FDC14,14.500,1,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store
...,...,...,...,...,...,...,...,...,...,...,...
14174,FDD23,9.500,1,0.048645,Starchy Foods,186.1898,OUT013,1987,High,Tier 3,Supermarket Type1
14175,FDP32,6.650,0,0.087847,Fruits and Vegetables,126.7678,OUT045,2002,Medium,Tier 2,Supermarket Type1
14176,FDO31,6.760,1,0.028977,Fruits and Vegetables,80.2960,OUT035,2004,Small,Tier 2,Supermarket Type1
14177,FDQ57,7.275,0,0.000000,Snack Foods,144.5760,OUT013,1987,High,Tier 3,Supermarket Type1
14178,FDX32,15.100,1,0.099375,Fruits and Vegetables,143.6786,OUT027,1985,Medium,Tier 3,Supermarket Type3
14179,FDC39,7.405,0,0.158425,Dairy,207.8296,OUT027,1985,Medium,Tier 3,Supermarket Type3
14180,FDU55,16.200,0,0.035911,Fruits and Vegetables,261.3278,OUT046,1997,Small,Tier 1,Supermarket Type1
14181,FDL45,15.600,0,0.037656,Snack Foods,123.4704,OUT013,1987,High,Tier 3,Supermarket Type1
14182,DRK37,5.000,0,0.044073,Soft Drinks,188.8530,OUT049,1999,Medium,Tier 1,Supermarket Type1
14183,FDK22,9.800,0,0.026065,Snack Foods,215.3850,OUT013,1987,High,Tier 3,Supermarket Type1
14184,DRG37,16.200,0,0.000000,Soft Drinks,155.7972,OUT027,1985,Medium,Tier 3,Supermarket Type3
14185,FDK22,9.800,0,0.026234,Snack Foods,214.3850,OUT017,2007,Medium,Tier 2,Supermarket Type1
14186,DRH36,16.200,0,0.033516,Soft Drinks,72.8696,OUT018,2009,Medium,Tier 3,Supermarket Type2
14187,DRC36,13.000,1,0.045168,Soft Drinks,173.4054,OUT018,2009,Medium,Tier 3,Supermarket Type2
14188,DRE03,19.600,0,0.024110,Dairy,46.0718,OUT027,1985,Medium,Tier 3,Supermarket Type3
14189,FDF34,9.300,1,0.014019,Snack Foods,196.9084,OUT046,1997,Small,Tier 1,Supermarket Type1
14190,FDZ22,9.395,0,0.045270,Snack Foods,82.1250,OUT046,1997,Small,Tier 1,Supermarket Type1
14191,FDC44,15.600,0,0.288892,Fruits and Vegetables,115.1518,OUT010,1998,Small,Tier 3,Grocery Store
14192,FDN31,11.500,0,0.072529,Fruits and Vegetables,188.0530,OUT027,1985,Medium,Tier 3,Supermarket Type3
14193,FDO03,10.395,1,0.037092,Meat,229.4352,OUT017,2007,Medium,Tier 2,Supermarket Type1
14194,FDA01,15.000,1,0.054463,Canned,59.5904,OUT049,1999,Medium,Tier 1,Supermarket Type1
14195,NCH42,6.860,0,0.036594,Household,231.1010,OUT049,1999,Medium,Tier 1,Supermarket Type1
14196,FDF46,7.070,0,0.094053,Snack Foods,116.0834,OUT018,2009,Medium,Tier 3,Supermarket Type2
14197,DRL35,15.700,0,0.030704,Hard Drinks,43.2770,OUT046,1997,Small,Tier 1,Supermarket Type1
14198,FDW46,13.000,1,0.070411,Snack Foods,63.4484,OUT049,1999,Medium,Tier 1,Supermarket Type1
14199,FDB58,10.500,1,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
14200,FDD47,7.600,1,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
14201,NCO17,10.000,0,0.073529,Health and Hygiene,118.7440,OUT045,2002,Medium,Tier 2,Supermarket Type1
14202,FDJ26,15.300,1,0.000000,Canned,214.6218,OUT017,2007,Medium,Tier 2,Supermarket Type1
14203,FDU37,9.500,1,0.104720,Canned,79.7960,OUT045,2002,Medium,Tier 2,Supermarket Type1

In [64]:
import datetime

combined['Outlet_Establishment_Year'] = datetime.datetime.now().year - combined['Outlet_Establishment_Year']

In [65]:
combined

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDA15,9.300,0,0.016047,Dairy,249.8092,OUT049,20,Medium,Tier 1,Supermarket Type1
1,DRC01,5.920,1,0.019278,Soft Drinks,48.2692,OUT018,10,Medium,Tier 3,Supermarket Type2
2,FDN15,17.500,0,0.016760,Meat,141.6180,OUT049,20,Medium,Tier 1,Supermarket Type1
3,FDX07,19.200,1,0.000000,Fruits and Vegetables,182.0950,OUT010,21,Small,Tier 3,Grocery Store
4,NCD19,8.930,0,0.000000,Household,53.8614,OUT013,32,High,Tier 3,Supermarket Type1
5,FDP36,10.395,1,0.000000,Baking Goods,51.4008,OUT018,10,Medium,Tier 3,Supermarket Type2
6,FDO10,13.650,1,0.012741,Snack Foods,57.6588,OUT013,32,High,Tier 3,Supermarket Type1
7,FDP10,19.000,0,0.127470,Snack Foods,107.7622,OUT027,34,Medium,Tier 3,Supermarket Type3
8,FDH17,16.200,1,0.016687,Frozen Foods,96.9726,OUT045,17,Medium,Tier 2,Supermarket Type1
9,FDU28,19.200,1,0.094450,Frozen Foods,187.8214,OUT017,12,Medium,Tier 2,Supermarket Type1
10,FDY07,11.800,0,0.000000,Fruits and Vegetables,45.5402,OUT049,20,Medium,Tier 1,Supermarket Type1
11,FDA03,18.500,1,0.045464,Dairy,144.1102,OUT046,22,Small,Tier 1,Supermarket Type1
12,FDX32,15.100,1,0.100014,Fruits and Vegetables,145.4786,OUT049,20,Medium,Tier 1,Supermarket Type1
13,FDS46,17.600,1,0.047257,Snack Foods,119.6782,OUT046,22,Small,Tier 1,Supermarket Type1
14,FDF32,16.350,0,0.068024,Fruits and Vegetables,196.4426,OUT013,32,High,Tier 3,Supermarket Type1
15,FDP49,9.000,1,0.069089,Breakfast,56.3614,OUT046,22,Small,Tier 1,Supermarket Type1
16,NCB42,11.800,0,0.008596,Health and Hygiene,115.3492,OUT018,10,Medium,Tier 3,Supermarket Type2
17,FDP49,9.000,1,0.069196,Breakfast,54.3614,OUT049,20,Medium,Tier 1,Supermarket Type1
18,DRI11,8.260,0,0.034238,Hard Drinks,113.2834,OUT027,34,Medium,Tier 3,Supermarket Type3
19,FDU02,13.350,0,0.102492,Dairy,230.5352,OUT035,15,Small,Tier 2,Supermarket Type1
20,FDN22,18.850,1,0.138190,Snack Foods,250.8724,OUT013,32,High,Tier 3,Supermarket Type1
21,FDW12,8.315,1,0.035400,Baking Goods,144.5444,OUT027,34,Medium,Tier 3,Supermarket Type3
22,NCB30,14.600,0,0.025698,Household,196.5084,OUT035,15,Small,Tier 2,Supermarket Type1
23,FDC37,15.500,0,0.057557,Baking Goods,107.6938,OUT019,34,Small,Tier 1,Grocery Store
24,FDR28,13.850,1,0.025896,Frozen Foods,165.0210,OUT046,22,Small,Tier 1,Supermarket Type1
25,NCD06,13.000,0,0.099887,Household,45.9060,OUT017,12,Medium,Tier 2,Supermarket Type1
26,FDV10,7.645,1,0.066693,Snack Foods,42.3112,OUT035,15,Small,Tier 2,Supermarket Type1
27,DRJ59,11.650,0,0.019356,Hard Drinks,39.1164,OUT013,32,High,Tier 3,Supermarket Type1
28,FDE51,5.925,1,0.161467,Dairy,45.5086,OUT010,21,Small,Tier 3,Grocery Store
29,FDC14,14.500,1,0.072222,Canned,43.6454,OUT019,34,Small,Tier 1,Grocery Store
...,...,...,...,...,...,...,...,...,...,...,...
14174,FDD23,9.500,1,0.048645,Starchy Foods,186.1898,OUT013,32,High,Tier 3,Supermarket Type1
14175,FDP32,6.650,0,0.087847,Fruits and Vegetables,126.7678,OUT045,17,Medium,Tier 2,Supermarket Type1
14176,FDO31,6.760,1,0.028977,Fruits and Vegetables,80.2960,OUT035,15,Small,Tier 2,Supermarket Type1
14177,FDQ57,7.275,0,0.000000,Snack Foods,144.5760,OUT013,32,High,Tier 3,Supermarket Type1
14178,FDX32,15.100,1,0.099375,Fruits and Vegetables,143.6786,OUT027,34,Medium,Tier 3,Supermarket Type3
14179,FDC39,7.405,0,0.158425,Dairy,207.8296,OUT027,34,Medium,Tier 3,Supermarket Type3
14180,FDU55,16.200,0,0.035911,Fruits and Vegetables,261.3278,OUT046,22,Small,Tier 1,Supermarket Type1
14181,FDL45,15.600,0,0.037656,Snack Foods,123.4704,OUT013,32,High,Tier 3,Supermarket Type1
14182,DRK37,5.000,0,0.044073,Soft Drinks,188.8530,OUT049,20,Medium,Tier 1,Supermarket Type1
14183,FDK22,9.800,0,0.026065,Snack Foods,215.3850,OUT013,32,High,Tier 3,Supermarket Type1
14184,DRG37,16.200,0,0.000000,Soft Drinks,155.7972,OUT027,34,Medium,Tier 3,Supermarket Type3
14185,FDK22,9.800,0,0.026234,Snack Foods,214.3850,OUT017,12,Medium,Tier 2,Supermarket Type1
14186,DRH36,16.200,0,0.033516,Soft Drinks,72.8696,OUT018,10,Medium,Tier 3,Supermarket Type2
14187,DRC36,13.000,1,0.045168,Soft Drinks,173.4054,OUT018,10,Medium,Tier 3,Supermarket Type2
14188,DRE03,19.600,0,0.024110,Dairy,46.0718,OUT027,34,Medium,Tier 3,Supermarket Type3
14189,FDF34,9.300,1,0.014019,Snack Foods,196.9084,OUT046,22,Small,Tier 1,Supermarket Type1
14190,FDZ22,9.395,0,0.045270,Snack Foods,82.1250,OUT046,22,Small,Tier 1,Supermarket Type1
14191,FDC44,15.600,0,0.288892,Fruits and Vegetables,115.1518,OUT010,21,Small,Tier 3,Grocery Store
14192,FDN31,11.500,0,0.072529,Fruits and Vegetables,188.0530,OUT027,34,Medium,Tier 3,Supermarket Type3
14193,FDO03,10.395,1,0.037092,Meat,229.4352,OUT017,12,Medium,Tier 2,Supermarket Type1
14194,FDA01,15.000,1,0.054463,Canned,59.5904,OUT049,20,Medium,Tier 1,Supermarket Type1
14195,NCH42,6.860,0,0.036594,Household,231.1010,OUT049,20,Medium,Tier 1,Supermarket Type1
14196,FDF46,7.070,0,0.094053,Snack Foods,116.0834,OUT018,10,Medium,Tier 3,Supermarket Type2
14197,DRL35,15.700,0,0.030704,Hard Drinks,43.2770,OUT046,22,Small,Tier 1,Supermarket Type1
14198,FDW46,13.000,1,0.070411,Snack Foods,63.4484,OUT049,20,Medium,Tier 1,Supermarket Type1
14199,FDB58,10.500,1,0.013496,Snack Foods,141.3154,OUT046,22,Small,Tier 1,Supermarket Type1
14200,FDD47,7.600,1,0.142991,Starchy Foods,169.1448,OUT018,10,Medium,Tier 3,Supermarket Type2
14201,NCO17,10.000,0,0.073529,Health and Hygiene,118.7440,OUT045,17,Medium,Tier 2,Supermarket Type1
14202,FDJ26,15.300,1,0.000000,Canned,214.6218,OUT017,12,Medium,Tier 2,Supermarket Type1
14203,FDU37,9.500,1,0.104720,Canned,79.7960,OUT045,17,Medium,Tier 2,Supermarket Type1

In [66]:
combined['Item_MRP'] -= combined['Item_MRP'].min()

In [67]:
combined['Item_MRP'] /= combined['Item_MRP'].max()

In [68]:
combined

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDA15,9.300,0,0.016047,Dairy,0.927507,OUT049,20,Medium,Tier 1,Supermarket Type1
1,DRC01,5.920,1,0.019278,Soft Drinks,0.072068,OUT018,10,Medium,Tier 3,Supermarket Type2
2,FDN15,17.500,0,0.016760,Meat,0.468288,OUT049,20,Medium,Tier 1,Supermarket Type1
3,FDX07,19.200,1,0.000000,Fruits and Vegetables,0.640093,OUT010,21,Small,Tier 3,Grocery Store
4,NCD19,8.930,0,0.000000,Household,0.095805,OUT013,32,High,Tier 3,Supermarket Type1
5,FDP36,10.395,1,0.000000,Baking Goods,0.085361,OUT018,10,Medium,Tier 3,Supermarket Type2
6,FDO10,13.650,1,0.012741,Snack Foods,0.111923,OUT013,32,High,Tier 3,Supermarket Type1
7,FDP10,19.000,0,0.127470,Snack Foods,0.324587,OUT027,34,Medium,Tier 3,Supermarket Type3
8,FDH17,16.200,1,0.016687,Frozen Foods,0.278791,OUT045,17,Medium,Tier 2,Supermarket Type1
9,FDU28,19.200,1,0.094450,Frozen Foods,0.664399,OUT017,12,Medium,Tier 2,Supermarket Type1
10,FDY07,11.800,0,0.000000,Fruits and Vegetables,0.060485,OUT049,20,Medium,Tier 1,Supermarket Type1
11,FDA03,18.500,1,0.045464,Dairy,0.478867,OUT046,22,Small,Tier 1,Supermarket Type1
12,FDX32,15.100,1,0.100014,Fruits and Vegetables,0.484675,OUT049,20,Medium,Tier 1,Supermarket Type1
13,FDS46,17.600,1,0.047257,Snack Foods,0.375165,OUT046,22,Small,Tier 1,Supermarket Type1
14,FDF32,16.350,0,0.068024,Fruits and Vegetables,0.700992,OUT013,32,High,Tier 3,Supermarket Type1
15,FDP49,9.000,1,0.069089,Breakfast,0.106416,OUT046,22,Small,Tier 1,Supermarket Type1
16,NCB42,11.800,0,0.008596,Health and Hygiene,0.356790,OUT018,10,Medium,Tier 3,Supermarket Type2
17,FDP49,9.000,1,0.069196,Breakfast,0.097927,OUT049,20,Medium,Tier 1,Supermarket Type1
18,DRI11,8.260,0,0.034238,Hard Drinks,0.348022,OUT027,34,Medium,Tier 3,Supermarket Type3
19,FDU02,13.350,0,0.102492,Dairy,0.845698,OUT035,15,Small,Tier 2,Supermarket Type1
20,FDN22,18.850,1,0.138190,Snack Foods,0.932020,OUT013,32,High,Tier 3,Supermarket Type1
21,FDW12,8.315,1,0.035400,Baking Goods,0.480710,OUT027,34,Medium,Tier 3,Supermarket Type3
22,NCB30,14.600,0,0.025698,Household,0.701271,OUT035,15,Small,Tier 2,Supermarket Type1
23,FDC37,15.500,0,0.057557,Baking Goods,0.324297,OUT019,34,Small,Tier 1,Grocery Store
24,FDR28,13.850,1,0.025896,Frozen Foods,0.567623,OUT046,22,Small,Tier 1,Supermarket Type1
25,NCD06,13.000,0,0.099887,Household,0.062038,OUT017,12,Medium,Tier 2,Supermarket Type1
26,FDV10,7.645,1,0.066693,Snack Foods,0.046780,OUT035,15,Small,Tier 2,Supermarket Type1
27,DRJ59,11.650,0,0.019356,Hard Drinks,0.033219,OUT013,32,High,Tier 3,Supermarket Type1
28,FDE51,5.925,1,0.161467,Dairy,0.060351,OUT010,21,Small,Tier 3,Grocery Store
29,FDC14,14.500,1,0.072222,Canned,0.052443,OUT019,34,Small,Tier 1,Grocery Store
...,...,...,...,...,...,...,...,...,...,...,...
14174,FDD23,9.500,1,0.048645,Starchy Foods,0.657474,OUT013,32,High,Tier 3,Supermarket Type1
14175,FDP32,6.650,0,0.087847,Fruits and Vegetables,0.405257,OUT045,17,Medium,Tier 2,Supermarket Type1
14176,FDO31,6.760,1,0.028977,Fruits and Vegetables,0.208007,OUT035,15,Small,Tier 2,Supermarket Type1
14177,FDQ57,7.275,0,0.000000,Snack Foods,0.480844,OUT013,32,High,Tier 3,Supermarket Type1
14178,FDX32,15.100,1,0.099375,Fruits and Vegetables,0.477035,OUT027,34,Medium,Tier 3,Supermarket Type3
14179,FDC39,7.405,0,0.158425,Dairy,0.749324,OUT027,34,Medium,Tier 3,Supermarket Type3
14180,FDU55,16.200,0,0.035911,Fruits and Vegetables,0.976398,OUT046,22,Small,Tier 1,Supermarket Type1
14181,FDL45,15.600,0,0.037656,Snack Foods,0.391261,OUT013,32,High,Tier 3,Supermarket Type1
14182,DRK37,5.000,0,0.044073,Soft Drinks,0.668778,OUT049,20,Medium,Tier 1,Supermarket Type1
14183,FDK22,9.800,0,0.026065,Snack Foods,0.781393,OUT013,32,High,Tier 3,Supermarket Type1
14184,DRG37,16.200,0,0.000000,Soft Drinks,0.528472,OUT027,34,Medium,Tier 3,Supermarket Type3
14185,FDK22,9.800,0,0.026234,Snack Foods,0.777149,OUT017,12,Medium,Tier 2,Supermarket Type1
14186,DRH36,16.200,0,0.033516,Soft Drinks,0.176485,OUT018,10,Medium,Tier 3,Supermarket Type2
14187,DRC36,13.000,1,0.045168,Soft Drinks,0.603210,OUT018,10,Medium,Tier 3,Supermarket Type2
14188,DRE03,19.600,0,0.024110,Dairy,0.062742,OUT027,34,Medium,Tier 3,Supermarket Type3
14189,FDF34,9.300,1,0.014019,Snack Foods,0.702969,OUT046,22,Small,Tier 1,Supermarket Type1
14190,FDZ22,9.395,0,0.045270,Snack Foods,0.215770,OUT046,22,Small,Tier 1,Supermarket Type1
14191,FDC44,15.600,0,0.288892,Fruits and Vegetables,0.355952,OUT010,21,Small,Tier 3,Grocery Store
14192,FDN31,11.500,0,0.072529,Fruits and Vegetables,0.665382,OUT027,34,Medium,Tier 3,Supermarket Type3
14193,FDO03,10.395,1,0.037092,Meat,0.841029,OUT017,12,Medium,Tier 2,Supermarket Type1
14194,FDA01,15.000,1,0.054463,Canned,0.120121,OUT049,20,Medium,Tier 1,Supermarket Type1
14195,NCH42,6.860,0,0.036594,Household,0.848100,OUT049,20,Medium,Tier 1,Supermarket Type1
14196,FDF46,7.070,0,0.094053,Snack Foods,0.359907,OUT018,10,Medium,Tier 3,Supermarket Type2
14197,DRL35,15.700,0,0.030704,Hard Drinks,0.050879,OUT046,22,Small,Tier 1,Supermarket Type1
14198,FDW46,13.000,1,0.070411,Snack Foods,0.136497,OUT049,20,Medium,Tier 1,Supermarket Type1
14199,FDB58,10.500,1,0.013496,Snack Foods,0.467004,OUT046,22,Small,Tier 1,Supermarket Type1
14200,FDD47,7.600,1,0.142991,Starchy Foods,0.585126,OUT018,10,Medium,Tier 3,Supermarket Type2
14201,NCO17,10.000,0,0.073529,Health and Hygiene,0.371199,OUT045,17,Medium,Tier 2,Supermarket Type1
14202,FDJ26,15.300,1,0.000000,Canned,0.778154,OUT017,12,Medium,Tier 2,Supermarket Type1
14203,FDU37,9.500,1,0.104720,Canned,0.205884,OUT045,17,Medium,Tier 2,Supermarket Type1

In [69]:
combined['Item_Weight'] -= combined['Item_Weight'].min()
combined['Item_Weight'] /= combined['Item_Weight'].max()

In [98]:
combined.shape

(14204, 11)

In [99]:
df_train.shape

(8523, 12)

In [100]:
df_test.shape

(5681, 11)

In [103]:
combined2 = combined

In [104]:
combined2.shape

(14204, 11)

In [105]:
combined2.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type'],
      dtype='object')

In [107]:
combined2.drop('Item_Identifier', inplace=True, axis=1)

In [108]:
combined2.shape

(14204, 10)

In [109]:
idx = combined.columns

In [115]:
idx = combined[['Item_Weight', 'Item_Fat_Content', 'Item_Visibility', 'Item_Type',
       'Item_MRP', 'Outlet_Identifier', 'Outlet_Establishment_Year',
       'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']]

In [116]:
idx

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,0.282525,0,0.016047,Dairy,0.927507,OUT049,20,Medium,Tier 1,Supermarket Type1
1,0.081274,1,0.019278,Soft Drinks,0.072068,OUT018,10,Medium,Tier 3,Supermarket Type2
2,0.770765,0,0.016760,Meat,0.468288,OUT049,20,Medium,Tier 1,Supermarket Type1
3,0.871986,1,0.000000,Fruits and Vegetables,0.640093,OUT010,21,Small,Tier 3,Grocery Store
4,0.260494,0,0.000000,Household,0.095805,OUT013,32,High,Tier 3,Supermarket Type1
5,0.347723,1,0.000000,Baking Goods,0.085361,OUT018,10,Medium,Tier 3,Supermarket Type2
6,0.541530,1,0.012741,Snack Foods,0.111923,OUT013,32,High,Tier 3,Supermarket Type1
7,0.860077,0,0.127470,Snack Foods,0.324587,OUT027,34,Medium,Tier 3,Supermarket Type3
8,0.693361,1,0.016687,Frozen Foods,0.278791,OUT045,17,Medium,Tier 2,Supermarket Type1
9,0.871986,1,0.094450,Frozen Foods,0.664399,OUT017,12,Medium,Tier 2,Supermarket Type1
10,0.431378,0,0.000000,Fruits and Vegetables,0.060485,OUT049,20,Medium,Tier 1,Supermarket Type1
11,0.830307,1,0.045464,Dairy,0.478867,OUT046,22,Small,Tier 1,Supermarket Type1
12,0.627865,1,0.100014,Fruits and Vegetables,0.484675,OUT049,20,Medium,Tier 1,Supermarket Type1
13,0.776719,1,0.047257,Snack Foods,0.375165,OUT046,22,Small,Tier 1,Supermarket Type1
14,0.702292,0,0.068024,Fruits and Vegetables,0.700992,OUT013,32,High,Tier 3,Supermarket Type1
15,0.264662,1,0.069089,Breakfast,0.106416,OUT046,22,Small,Tier 1,Supermarket Type1
16,0.431378,0,0.008596,Health and Hygiene,0.356790,OUT018,10,Medium,Tier 3,Supermarket Type2
17,0.264662,1,0.069196,Breakfast,0.097927,OUT049,20,Medium,Tier 1,Supermarket Type1
18,0.220601,0,0.034238,Hard Drinks,0.348022,OUT027,34,Medium,Tier 3,Supermarket Type3
19,0.523668,0,0.102492,Dairy,0.845698,OUT035,15,Small,Tier 2,Supermarket Type1
20,0.851146,1,0.138190,Snack Foods,0.932020,OUT013,32,High,Tier 3,Supermarket Type1
21,0.223876,1,0.035400,Baking Goods,0.480710,OUT027,34,Medium,Tier 3,Supermarket Type3
22,0.598095,0,0.025698,Household,0.701271,OUT035,15,Small,Tier 2,Supermarket Type1
23,0.651682,0,0.057557,Baking Goods,0.324297,OUT019,34,Small,Tier 1,Grocery Store
24,0.553439,1,0.025896,Frozen Foods,0.567623,OUT046,22,Small,Tier 1,Supermarket Type1
25,0.502828,0,0.099887,Household,0.062038,OUT017,12,Medium,Tier 2,Supermarket Type1
26,0.183983,1,0.066693,Snack Foods,0.046780,OUT035,15,Small,Tier 2,Supermarket Type1
27,0.422447,0,0.019356,Hard Drinks,0.033219,OUT013,32,High,Tier 3,Supermarket Type1
28,0.081572,1,0.161467,Dairy,0.060351,OUT010,21,Small,Tier 3,Grocery Store
29,0.592141,1,0.072222,Canned,0.052443,OUT019,34,Small,Tier 1,Grocery Store
...,...,...,...,...,...,...,...,...,...,...
14174,0.294433,1,0.048645,Starchy Foods,0.657474,OUT013,32,High,Tier 3,Supermarket Type1
14175,0.124740,0,0.087847,Fruits and Vegetables,0.405257,OUT045,17,Medium,Tier 2,Supermarket Type1
14176,0.131289,1,0.028977,Fruits and Vegetables,0.208007,OUT035,15,Small,Tier 2,Supermarket Type1
14177,0.161953,0,0.000000,Snack Foods,0.480844,OUT013,32,High,Tier 3,Supermarket Type1
14178,0.627865,1,0.099375,Fruits and Vegetables,0.477035,OUT027,34,Medium,Tier 3,Supermarket Type3
14179,0.169693,0,0.158425,Dairy,0.749324,OUT027,34,Medium,Tier 3,Supermarket Type3
14180,0.693361,0,0.035911,Fruits and Vegetables,0.976398,OUT046,22,Small,Tier 1,Supermarket Type1
14181,0.657636,0,0.037656,Snack Foods,0.391261,OUT013,32,High,Tier 3,Supermarket Type1
14182,0.026496,0,0.044073,Soft Drinks,0.668778,OUT049,20,Medium,Tier 1,Supermarket Type1
14183,0.312295,0,0.026065,Snack Foods,0.781393,OUT013,32,High,Tier 3,Supermarket Type1
14184,0.693361,0,0.000000,Soft Drinks,0.528472,OUT027,34,Medium,Tier 3,Supermarket Type3
14185,0.312295,0,0.026234,Snack Foods,0.777149,OUT017,12,Medium,Tier 2,Supermarket Type1
14186,0.693361,0,0.033516,Soft Drinks,0.176485,OUT018,10,Medium,Tier 3,Supermarket Type2
14187,0.502828,1,0.045168,Soft Drinks,0.603210,OUT018,10,Medium,Tier 3,Supermarket Type2
14188,0.895802,0,0.024110,Dairy,0.062742,OUT027,34,Medium,Tier 3,Supermarket Type3
14189,0.282525,1,0.014019,Snack Foods,0.702969,OUT046,22,Small,Tier 1,Supermarket Type1
14190,0.288181,0,0.045270,Snack Foods,0.215770,OUT046,22,Small,Tier 1,Supermarket Type1
14191,0.657636,0,0.288892,Fruits and Vegetables,0.355952,OUT010,21,Small,Tier 3,Grocery Store
14192,0.413516,0,0.072529,Fruits and Vegetables,0.665382,OUT027,34,Medium,Tier 3,Supermarket Type3
14193,0.347723,1,0.037092,Meat,0.841029,OUT017,12,Medium,Tier 2,Supermarket Type1
14194,0.621911,1,0.054463,Canned,0.120121,OUT049,20,Medium,Tier 1,Supermarket Type1
14195,0.137243,0,0.036594,Household,0.848100,OUT049,20,Medium,Tier 1,Supermarket Type1
14196,0.149747,0,0.094053,Snack Foods,0.359907,OUT018,10,Medium,Tier 3,Supermarket Type2
14197,0.663590,0,0.030704,Hard Drinks,0.050879,OUT046,22,Small,Tier 1,Supermarket Type1
14198,0.502828,1,0.070411,Snack Foods,0.136497,OUT049,20,Medium,Tier 1,Supermarket Type1
14199,0.353974,1,0.013496,Snack Foods,0.467004,OUT046,22,Small,Tier 1,Supermarket Type1
14200,0.181304,1,0.142991,Starchy Foods,0.585126,OUT018,10,Medium,Tier 3,Supermarket Type2
14201,0.324204,0,0.073529,Health and Hygiene,0.371199,OUT045,17,Medium,Tier 2,Supermarket Type1
14202,0.639774,1,0.000000,Canned,0.778154,OUT017,12,Medium,Tier 2,Supermarket Type1
14203,0.294433,1,0.104720,Canned,0.205884,OUT045,17,Medium,Tier 2,Supermarket Type1

In [117]:
combined2 = pd.get_dummies(idx)

In [118]:
combined2.shape

(14204, 41)

In [120]:
train = combined2[:8523]
test = combined2[8523:]
target = df_train['Item_Outlet_Sales']

In [121]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(train,target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [122]:
print(model.intercept_)

-223.15761682391394

In [123]:
y_pred = model.predict(test)

In [125]:
y_pred.shape

(5681,)

In [126]:
df = pd.DataFrame(y_pred)

In [127]:
df

                0
0     1840.369113
1     1528.576040
2     1882.082328
3     2578.201918
4     5136.377185
5     1951.976282
6      596.409071
7     2783.708630
8     1489.150029
9     3088.631617
10    2022.365635
11    1333.723093
12    1869.334078
13    2055.208722
14     912.654229
15    2550.943777
16    3270.893457
17    2753.548979
18    3185.508526
19    1115.276831
20    2827.988849
21    3878.771906
22     773.101996
23     374.957694
24    3012.924173
25    1449.097667
26     912.252503
27    2521.912943
28    3827.702669
29    2058.146827
...           ...
5651  3052.971306
5652  1983.198461
5653  1532.209652
5654  2346.659030
5655  3803.585549
5656  4672.036032
5657  4164.395143
5658  2007.518099
5659  3072.612148
5660  3441.086751
5661  3924.946126
5662  3498.912175
5663   897.139412
5664  2498.817774
5665  2196.339657
5666  3167.382753
5667  1330.614765
5668   -94.169794
5669  4461.323322
5670  3781.687593
5671  1152.250186
5672  3720.338166
5673  1566.204615
5674   742.959605
5675  1169.991655
5676  2302.380677
5677  2450.441227
5678  1822.654632
5679  3589.103262
5680  1284.174318

[5681 rows x 1 columns]

In [131]:
test_cases=pd.read_csv('Test.csv')
df['Item_Identifier'] = test_cases['Item_Identifier']
df['Outlet_Identifier'] = test_cases['Outlet_Identifier']
df['Item_Outlet_Sales'] = df[0]

In [133]:
df[['Item_Identifier', 'Outlet_Identifier', 'Item_Outlet_Sales']].to_csv('Result.csv',index=False)